[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["node node_modules/prisma/build/index.js generate"]

[start]
cmd = "node scripts/reset-migrations.js && node node_modules/prisma/build/index.js migrate deploy && node prisma/seed.js && node src/server.js"
